export const SELECT_PROJECT = 'SELECT_PROJECT';
export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';
export const REQUEST_REFRESH_PROJECT = 'REQUEST_REFRESH_PROJECT';
export const RECEIVE_REFRESH_PROJECT = 'RECEIVE_REFRESH_PROJECT';
export const REQUEST_REFRESH_PROJECT_FAILED = 'REQUEST_REFRESH_PROJECT_FAILED';
